/**
 * Insights Service Approval APIs
 * APIs to query approval service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ActionIn model module.
 * @module model/ActionIn
 * @version 1.0.0
 */
class ActionIn {
    /**
     * Constructs a new <code>ActionIn</code>.
     * Input parameters for Action object
     * @alias module:model/ActionIn
     * @param operation {module:model/ActionIn.OperationEnum} Types of action, may be one of the value (approve, deny, notify, memo, or skip). The stage will be updated according to the operation.
     */
    constructor(operation) { 
        
        ActionIn.initialize(this, operation);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, operation) { 
        obj['operation'] = operation;
    }

    /**
     * Constructs a <code>ActionIn</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActionIn} obj Optional instance to populate.
     * @return {module:model/ActionIn} The populated <code>ActionIn</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActionIn();

            if (data.hasOwnProperty('processed_by')) {
                obj['processed_by'] = ApiClient.convertToType(data['processed_by'], 'String');
            }
            if (data.hasOwnProperty('operation')) {
                obj['operation'] = ApiClient.convertToType(data['operation'], 'String');
            }
            if (data.hasOwnProperty('comments')) {
                obj['comments'] = ApiClient.convertToType(data['comments'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The person who performs the action
 * @member {String} processed_by
 */
ActionIn.prototype['processed_by'] = undefined;

/**
 * Types of action, may be one of the value (approve, deny, notify, memo, or skip). The stage will be updated according to the operation.
 * @member {module:model/ActionIn.OperationEnum} operation
 * @default 'memo'
 */
ActionIn.prototype['operation'] = 'memo';

/**
 * Comments for action
 * @member {String} comments
 */
ActionIn.prototype['comments'] = undefined;





/**
 * Allowed values for the <code>operation</code> property.
 * @enum {String}
 * @readonly
 */
ActionIn['OperationEnum'] = {

    /**
     * value: "approve"
     * @const
     */
    "approve": "approve",

    /**
     * value: "deny"
     * @const
     */
    "deny": "deny",

    /**
     * value: "notify"
     * @const
     */
    "notify": "notify",

    /**
     * value: "memo"
     * @const
     */
    "memo": "memo",

    /**
     * value: "skip"
     * @const
     */
    "skip": "skip"
};



export default ActionIn;

