/**
 * Insights Service Approval APIs
 * APIs to query approval service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Operation from './Operation';

/**
 * The Action model module.
 * @module model/Action
 * @version 1.0.0
 */
class Action {
    /**
     * Constructs a new <code>Action</code>.
     * Action is kind of like processing record. Each stage may have many actions before final decision.
     * @alias module:model/Action
     * @param processedBy {String} Processor info who perform the action
     */
    constructor(processedBy) { 
        
        Action.initialize(this, processedBy);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, processedBy) { 
        obj['processed_by'] = processedBy;
    }

    /**
     * Constructs a <code>Action</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Action} obj Optional instance to populate.
     * @return {module:model/Action} The populated <code>Action</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Action();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('processed_by')) {
                obj['processed_by'] = ApiClient.convertToType(data['processed_by'], 'String');
            }
            if (data.hasOwnProperty('operation')) {
                obj['operation'] = Operation.constructFromObject(data['operation']);
            }
            if (data.hasOwnProperty('comments')) {
                obj['comments'] = ApiClient.convertToType(data['comments'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Action.prototype['id'] = undefined;

/**
 * Processor info who perform the action
 * @member {String} processed_by
 */
Action.prototype['processed_by'] = undefined;

/**
 * @member {module:model/Operation} operation
 */
Action.prototype['operation'] = undefined;

/**
 * Comments for action
 * @member {String} comments
 */
Action.prototype['comments'] = undefined;

/**
 * Timestamp of creation
 * @member {Date} created_at
 */
Action.prototype['created_at'] = undefined;






export default Action;

