/**
 * Insights Service Approval APIs
 * APIs to query approval service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GroupIn from './GroupIn';

/**
 * The GroupOut model module.
 * @module model/GroupOut
 * @version 1.0.0
 */
class GroupOut {
    /**
     * Constructs a new <code>GroupOut</code>.
     * User groups.
     * @alias module:model/GroupOut
     * @extends module:model/GroupIn
     * @implements module:model/GroupIn
     * @param name {} Group name
     */
    constructor(name) { 
        GroupIn.initialize(this, name);
        GroupOut.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
    }

    /**
     * Constructs a <code>GroupOut</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GroupOut} obj Optional instance to populate.
     * @return {module:model/GroupOut} The populated <code>GroupOut</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GroupOut();
            GroupIn.constructFromObject(data, obj);
            GroupIn.constructFromObject(data, obj);

        }
        return obj;
    }


}


// Implement GroupIn interface:
/**
 * Group name
 * @member {String} name
 */
GroupIn.prototype['name'] = undefined;




export default GroupOut;

