/**
 * Insights Service Approval APIs
 * APIs to query approval service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GroupOperationIn model module.
 * @module model/GroupOperationIn
 * @version 1.0.0
 */
class GroupOperationIn {
    /**
     * Constructs a new <code>GroupOperationIn</code>.
     * Operation type and parameters to a given group
     * @alias module:model/GroupOperationIn
     * @param operation {module:model/GroupOperationIn.OperationEnum} Types of group operation, may be either join_users or withdraw_users.
     * @param parameters {Object} JSON object. Currently user ids in the group
     */
    constructor(operation, parameters) { 
        
        GroupOperationIn.initialize(this, operation, parameters);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, operation, parameters) { 
        obj['operation'] = operation;
        obj['parameters'] = parameters;
    }

    /**
     * Constructs a <code>GroupOperationIn</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GroupOperationIn} obj Optional instance to populate.
     * @return {module:model/GroupOperationIn} The populated <code>GroupOperationIn</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GroupOperationIn();

            if (data.hasOwnProperty('operation')) {
                obj['operation'] = ApiClient.convertToType(data['operation'], 'String');
            }
            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = ApiClient.convertToType(data['parameters'], Object);
            }
        }
        return obj;
    }


}

/**
 * Types of group operation, may be either join_users or withdraw_users.
 * @member {module:model/GroupOperationIn.OperationEnum} operation
 */
GroupOperationIn.prototype['operation'] = undefined;

/**
 * JSON object. Currently user ids in the group
 * @member {Object} parameters
 */
GroupOperationIn.prototype['parameters'] = undefined;





/**
 * Allowed values for the <code>operation</code> property.
 * @enum {String}
 * @readonly
 */
GroupOperationIn['OperationEnum'] = {

    /**
     * value: "join_users"
     * @const
     */
    "join_users": "join_users",

    /**
     * value: "withdraw_users"
     * @const
     */
    "withdraw_users": "withdraw_users"
};



export default GroupOperationIn;

