/**
 * Insights Service Approval APIs
 * APIs to query approval service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GroupOut model module.
 * @module model/GroupOut
 * @version 1.0.0
 */
class GroupOut {
    /**
     * Constructs a new <code>GroupOut</code>.
     * User groups.
     * @alias module:model/GroupOut
     */
    constructor() { 
        
        GroupOut.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GroupOut</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GroupOut} obj Optional instance to populate.
     * @return {module:model/GroupOut} The populated <code>GroupOut</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GroupOut();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('user_ids')) {
                obj['user_ids'] = ApiClient.convertToType(data['user_ids'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
GroupOut.prototype['id'] = undefined;

/**
 * Group name
 * @member {String} name
 */
GroupOut.prototype['name'] = undefined;

/**
 * @member {Array.<String>} user_ids
 */
GroupOut.prototype['user_ids'] = undefined;






export default GroupOut;

