/**
 * Insights Service Approval APIs
 * APIs to query approval service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GroupIn model module.
 * @module model/GroupIn
 * @version 1.0.0
 */
class GroupIn {
    /**
     * Constructs a new <code>GroupIn</code>.
     * Input parameters for Group object
     * @alias module:model/GroupIn
     * @param name {String} Group name
     */
    constructor(name) { 
        
        GroupIn.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>GroupIn</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GroupIn} obj Optional instance to populate.
     * @return {module:model/GroupIn} The populated <code>GroupIn</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GroupIn();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Group name
 * @member {String} name
 */
GroupIn.prototype['name'] = undefined;






export default GroupIn;

