/**
 * Insights Service Approval APIs
 * APIs to query approval service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Operation.
* @enum {}
* @readonly
*/
export default class Operation {
    
        /**
         * value: "approve"
         * @const
         */
        "approve" = "approve";

    
        /**
         * value: "deny"
         * @const
         */
        "deny" = "deny";

    
        /**
         * value: "notify"
         * @const
         */
        "notify" = "notify";

    
        /**
         * value: "memo"
         * @const
         */
        "memo" = "memo";

    
        /**
         * value: "skip"
         * @const
         */
        "skip" = "skip";

    

    /**
    * Returns a <code>Operation</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Operation} The enum <code>Operation</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

