/**
 * Insights Service Approval APIs
 * APIs to query approval service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RequestIn model module.
 * @module model/RequestIn
 * @version 1.0.0
 */
class RequestIn {
    /**
     * Constructs a new <code>RequestIn</code>.
     * Input parameters for approval request object.
     * @alias module:model/RequestIn
     * @param name {String} Request name
     * @param content {Object} JSON object with request content
     */
    constructor(name, content) { 
        
        RequestIn.initialize(this, name, content);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, content) { 
        obj['name'] = name;
        obj['content'] = content;
    }

    /**
     * Constructs a <code>RequestIn</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RequestIn} obj Optional instance to populate.
     * @return {module:model/RequestIn} The populated <code>RequestIn</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RequestIn();

            if (data.hasOwnProperty('requester')) {
                obj['requester'] = ApiClient.convertToType(data['requester'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], Object);
            }
        }
        return obj;
    }


}

/**
 * Requester id
 * @member {String} requester
 */
RequestIn.prototype['requester'] = undefined;

/**
 * Request name
 * @member {String} name
 */
RequestIn.prototype['name'] = undefined;

/**
 * Request description
 * @member {String} description
 */
RequestIn.prototype['description'] = undefined;

/**
 * JSON object with request content
 * @member {Object} content
 */
RequestIn.prototype['content'] = undefined;






export default RequestIn;

