/**
 * Insights Service Approval APIs
 * APIs to query approval service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RequestIn from './RequestIn';

/**
 * The RequestOut model module.
 * @module model/RequestOut
 * @version 1.0.0
 */
class RequestOut {
    /**
     * Constructs a new <code>RequestOut</code>.
     * Approval request. Each request will associate with a workflow. Corresponding to the groups of the associated workflow, every request will have a list of stages to record the request processing details.
     * @alias module:model/RequestOut
     * @extends module:model/RequestIn
     * @implements module:model/RequestIn
     * @param name {} Request name
     * @param content {} JSON object with request content
     */
    constructor(name, content) { 
        RequestIn.initialize(this, name, content);
        RequestOut.initialize(this, name, content);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, content) { 
    }

    /**
     * Constructs a <code>RequestOut</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RequestOut} obj Optional instance to populate.
     * @return {module:model/RequestOut} The populated <code>RequestOut</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RequestOut();
            RequestIn.constructFromObject(data, obj);
            RequestIn.constructFromObject(data, obj);

        }
        return obj;
    }


}


// Implement RequestIn interface:
/**
 * Requester id
 * @member {String} requester
 */
RequestIn.prototype['requester'] = undefined;
/**
 * Request name
 * @member {String} name
 */
RequestIn.prototype['name'] = undefined;
/**
 * Request description
 * @member {String} description
 */
RequestIn.prototype['description'] = undefined;
/**
 * JSON object with request content
 * @member {Object} content
 */
RequestIn.prototype['content'] = undefined;




export default RequestOut;

