/**
 * Insights Service Approval APIs
 * APIs to query approval service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Decision from './Decision';
import State from './State';

/**
 * The Stage model module.
 * @module model/Stage
 * @version 1.0.0
 */
class Stage {
    /**
     * Constructs a new <code>Stage</code>.
     * The stage of approval request.
     * @alias module:model/Stage
     * @param groupId {String} Associated group id
     */
    constructor(groupId) { 
        
        Stage.initialize(this, groupId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, groupId) { 
        obj['group_id'] = groupId;
    }

    /**
     * Constructs a <code>Stage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Stage} obj Optional instance to populate.
     * @return {module:model/Stage} The populated <code>Stage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Stage();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = State.constructFromObject(data['state']);
            }
            if (data.hasOwnProperty('decision')) {
                obj['decision'] = Decision.constructFromObject(data['decision']);
            }
            if (data.hasOwnProperty('comments')) {
                obj['comments'] = ApiClient.convertToType(data['comments'], 'String');
            }
            if (data.hasOwnProperty('group_id')) {
                obj['group_id'] = ApiClient.convertToType(data['group_id'], 'String');
            }
            if (data.hasOwnProperty('request_id')) {
                obj['request_id'] = ApiClient.convertToType(data['request_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Stage.prototype['id'] = undefined;

/**
 * @member {module:model/State} state
 */
Stage.prototype['state'] = undefined;

/**
 * @member {module:model/Decision} decision
 */
Stage.prototype['decision'] = undefined;

/**
 * Approval stage
 * @member {String} comments
 */
Stage.prototype['comments'] = undefined;

/**
 * Associated group id
 * @member {String} group_id
 */
Stage.prototype['group_id'] = undefined;

/**
 * Associated request id
 * @member {String} request_id
 */
Stage.prototype['request_id'] = undefined;






export default Stage;

