/**
 * Insights Service Approval APIs
 * APIs to query approval service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import StageIn from './StageIn';

/**
 * The StageOut model module.
 * @module model/StageOut
 * @version 1.0.0
 */
class StageOut {
    /**
     * Constructs a new <code>StageOut</code>.
     * The stage of approval request.
     * @alias module:model/StageOut
     * @extends module:model/StageIn
     * @implements module:model/StageIn
     * @param groupId {} Associated group id
     * @param state {} The state of stage or request. It may be one of values (pending, skipped, notified or finished)
     * @param decision {} Final decision, may be one of the value (undecided, approved, or denied)
     */
    constructor(groupId, state, decision) { 
        StageIn.initialize(this, groupId, state, decision);
        StageOut.initialize(this, groupId, state, decision);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, groupId, state, decision) { 
    }

    /**
     * Constructs a <code>StageOut</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StageOut} obj Optional instance to populate.
     * @return {module:model/StageOut} The populated <code>StageOut</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StageOut();
            StageIn.constructFromObject(data, obj);
            StageIn.constructFromObject(data, obj);

        }
        return obj;
    }


}


// Implement StageIn interface:
/**
 * Associated group id
 * @member {String} group_id
 */
StageIn.prototype['group_id'] = undefined;
/**
 * The state of stage or request. It may be one of values (pending, skipped, notified or finished)
 * @member {module:model/StageIn.StateEnum} state
 * @default 'pending'
 */
StageIn.prototype['state'] = 'pending';
/**
 * Final decision, may be one of the value (undecided, approved, or denied)
 * @member {module:model/StageIn.DecisionEnum} decision
 * @default 'undecided'
 */
StageIn.prototype['decision'] = 'undecided';




export default StageOut;

