/**
 * Insights Service Approval APIs
 * APIs to query approval service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TemplateIn from './TemplateIn';

/**
 * The TemplateOut model module.
 * @module model/TemplateOut
 * @version 1.0.0
 */
class TemplateOut {
    /**
     * Constructs a new <code>TemplateOut</code>.
     * The template to categorize workflows.
     * @alias module:model/TemplateOut
     * @extends module:model/TemplateIn
     * @implements module:model/TemplateIn
     * @param title {} 
     */
    constructor(title) { 
        TemplateIn.initialize(this, title);
        TemplateOut.initialize(this, title);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, title) { 
    }

    /**
     * Constructs a <code>TemplateOut</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TemplateOut} obj Optional instance to populate.
     * @return {module:model/TemplateOut} The populated <code>TemplateOut</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TemplateOut();
            TemplateIn.constructFromObject(data, obj);
            TemplateIn.constructFromObject(data, obj);

        }
        return obj;
    }


}


// Implement TemplateIn interface:
/**
 * @member {String} title
 */
TemplateIn.prototype['title'] = undefined;




export default TemplateOut;

