/**
 * Insights Service Approval APIs
 * APIs to query approval service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserIn model module.
 * @module model/UserIn
 * @version 1.0.0
 */
class UserIn {
    /**
     * Constructs a new <code>UserIn</code>.
     * Input parameters for User object
     * @alias module:model/UserIn
     * @param email {String} Email address of the user
     */
    constructor(email) { 
        
        UserIn.initialize(this, email);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email) { 
        obj['email'] = email;
    }

    /**
     * Constructs a <code>UserIn</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserIn} obj Optional instance to populate.
     * @return {module:model/UserIn} The populated <code>UserIn</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserIn();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Email address of the user
 * @member {String} email
 */
UserIn.prototype['email'] = undefined;

/**
 * @member {String} first_name
 */
UserIn.prototype['first_name'] = undefined;

/**
 * @member {String} last_name
 */
UserIn.prototype['last_name'] = undefined;






export default UserIn;

