/**
 * Insights Service Approval APIs
 * APIs to query approval service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserIn from './UserIn';

/**
 * The UserOut model module.
 * @module model/UserOut
 * @version 1.0.0
 */
class UserOut {
    /**
     * Constructs a new <code>UserOut</code>.
     * @alias module:model/UserOut
     * @extends module:model/UserIn
     * @implements module:model/UserIn
     * @param email {} Email address of the user
     */
    constructor(email) { 
        UserIn.initialize(this, email);
        UserOut.initialize(this, email);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email) { 
    }

    /**
     * Constructs a <code>UserOut</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserOut} obj Optional instance to populate.
     * @return {module:model/UserOut} The populated <code>UserOut</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserOut();
            UserIn.constructFromObject(data, obj);
            UserIn.constructFromObject(data, obj);

        }
        return obj;
    }


}


// Implement UserIn interface:
/**
 * Email address of the user
 * @member {String} email
 */
UserIn.prototype['email'] = undefined;
/**
 * @member {String} first_name
 */
UserIn.prototype['first_name'] = undefined;
/**
 * @member {String} last_name
 */
UserIn.prototype['last_name'] = undefined;




export default UserOut;

