/**
 * Insights Service Approval APIs
 * APIs to query approval service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WorkflowParameters model module.
 * @module model/WorkflowParameters
 * @version 1.0.0
 */
class WorkflowParameters {
    /**
     * Constructs a new <code>WorkflowParameters</code>.
     * Parameters to create a workflow
     * @alias module:model/WorkflowParameters
     * @param name {String} 
     * @param groupIds {Array.<Number>} 
     */
    constructor(name, groupIds) { 
        
        WorkflowParameters.initialize(this, name, groupIds);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, groupIds) { 
        obj['name'] = name;
        obj['group_ids'] = groupIds;
    }

    /**
     * Constructs a <code>WorkflowParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkflowParameters} obj Optional instance to populate.
     * @return {module:model/WorkflowParameters} The populated <code>WorkflowParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkflowParameters();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('group_ids')) {
                obj['group_ids'] = ApiClient.convertToType(data['group_ids'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
WorkflowParameters.prototype['name'] = undefined;

/**
 * @member {String} description
 */
WorkflowParameters.prototype['description'] = undefined;

/**
 * @member {Array.<Number>} group_ids
 */
WorkflowParameters.prototype['group_ids'] = undefined;






export default WorkflowParameters;

